- name: Remove Xfce configuration files
  file:
    path: "{{ xfce_configuration_path }}"
    state: absent

- name: Symlink Xfce configuration files
  file:
    src: "{{ role_path }}/files/"
    dest: "{{ xfce_configuration_path }}"
    state: link
