---
- hosts: all
  tasks:
    - name: Install Git
      apt: name=git-core state=present

    - name: Remove Git config
      file:
        path: "{{ ansible_env.HOME }}/.gitconfig"
        state: absent

    - name: Symlink Git config
      file:
        src: "{{ playbook_dir }}/config/.gitconfig"
        dest: "{{ ansible_env.HOME }}/.gitconfig"
        state: link
